#!/bin/bash -u

echo "Get crypto info and enode initial validator..."
BESU_NODE_PERM_ACCOUNT="0x"$(cat ../deploy/cryptofiles/admin/key.address)
BESU_NODE_PERM_KEY=$(cat ../deploy/cryptofiles/admin/key)
BESU_NODE_PERM_ENDPOINT="http://127.0.0.1:8545"
INITIAL_ADMIN_ACCOUNTS=${BESU_NODE_PERM_ACCOUNT}
INITIAL_ALLOWLISTED_NODES=$(paste -d, $(ls ../deploy/cryptofiles/node*/enode))

#RETAIN_ADMIN_CONTRACT=true
#RETAIN_NODE_RULES_CONTRACT=true
#RETAIN_ACCOUNT_RULES_CONTRACT=true

echo "BESU_NODE_PERM_ACCOUNT="$BESU_NODE_PERM_ACCOUNT
echo "BESU_NODE_PERM_KEY="$BESU_NODE_PERM_KEY
echo "BESU_NODE_PERM_ENDPOINT="$BESU_NODE_PERM_ENDPOINT
echo "INITIAL_ADMIN_ACCOUNTS="$INITIAL_ADMIN_ACCOUNTS
echo "INITIAL_ALLOWLISTED_NODES="$INITIAL_ALLOWLISTED_NODES

echo "Migrating contracts..."
cd ../deploy/permissioning-smart-contracts

NODE_INGRESS_CONTRACT_ADDRESS="0x0000000000000000000000000000000000009999" \
 ACCOUNT_INGRESS_CONTRACT_ADDRESS="0x0000000000000000000000000000000000008888" \
  BESU_NODE_PERM_ACCOUNT=${BESU_NODE_PERM_ACCOUNT} \
   BESU_NODE_PERM_KEY=${BESU_NODE_PERM_KEY} \
    BESU_NODE_PERM_ENDPOINT=${BESU_NODE_PERM_ENDPOINT} \
     INITIAL_ADMIN_ACCOUNTS=${INITIAL_ADMIN_ACCOUNTS} \
       INITIAL_ALLOWLISTED_NODES=${INITIAL_ALLOWLISTED_NODES} \
        yarn truffle migrate --reset


